services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_SERVER_BASE_URL: ${VITE_SERVER_BASE_URL}
    ports:
      - 3000:80
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 8000:8000
    networks:
      - app-network
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - db-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
